environment:
  VisualStudioVersion: 11.0

# TODO: add x64, fix issue: LNK1158: cannot run 'cvtres.exe'
platform:
- Win32

# TODO: add VSDebug
configuration:
- Release

install:
- cmd: git clone https://github.com/libyal/libyal.git && move libyal ..\
- ps: .\synczlib.ps1
- ps: .\syncwinflexbison.ps1
- ps: Invoke-WebRequest http://www.cygwin.com/setup-x86.exe -OutFile ..\setup-x86.exe
- cmd: ..\setup-x86.exe -qnNdO -R C:\cygwin -s http://cygwin.mirror.constant.com -l C:\cygwin\var\cache\setup -P bison -P flex
- cmd: git clone https://github.com/joachimmetz/dokan.git && move dokan ..\

before_build:
- cmd: xcopy /q /s C:\projects\libfvde C:\cygwin\home\appveyor\
- cmd: xcopy /q /s C:\projects\libfvde C:\msys64\home\appveyor\

build_script:
- ps: .\synclibs.ps1
- ps: .\autogen.ps1
- cmd: >-
    rem Prepare Visual Studio 2010 build

    C:\Python27\python.exe ..\libyal\scripts\msvscpp-convert.py --to 2010 msvscpp\libfvde.sln

    rem Build with Visual Studio 2010

    msbuild vs2010\libfvde.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    rem Prepare Visual Studio 2012 build

    C:\Python27\python.exe ..\libyal\scripts\msvscpp-convert.py --to 2012 msvscpp\libfvde.sln

    rem Build with Visual Studio 2012

    msbuild vs2012\libfvde.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    rem Prepare Visual Studio 2013 build

    C:\Python27\python.exe ..\libyal\scripts\msvscpp-convert.py --to 2013 msvscpp\libfvde.sln

    rem Build with Visual Studio 2013

    msbuild vs2013\libfvde.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    rem Prepare Cygwin build

    C:\cygwin\bin\bash -e -l -c "cd libfvde"

    C:\cygwin\bin\bash -e -l -c "./synclibs.sh && ./autogen.sh"

    rem Build with Cygwin

    C:\cygwin\bin\bash -e -l -c "./configure && make -j4"

    rem Prepare MinGW build

    C:\msys64\usr\bin\bash -e -l -c "cd libfvde"

    C:\msys64\usr\bin\bash -e -l -c "./synclibs.sh && ./autogen.sh"

    rem Build with MinGW 32-bit

    C:\msys64\usr\bin\bash -e -l -c "./configure --host=i686-w64-mingw32 && make -j4"

    rem Build with MinGW 64-bit

    C:\msys64\usr\bin\bash -e -l -c "./configure --host=x86_64-w64-mingw32 && make -j4"

    rem Run tests

test_script:
- ps: .\runtests.ps1

