environment:
  matrix:
  - TARGET: vs2008
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VisualStudioVersion: 9.0
  - TARGET: vs2010
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VisualStudioVersion: 10.0
  - TARGET: vs2012
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VisualStudioVersion: 11.0
  - TARGET: vs2013
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VisualStudioVersion: 12.0
  - TARGET: vs2015
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VisualStudioVersion: 14.0
  - TARGET: cygwin
  - TARGET: mingw32
  - TARGET: mingw64

# TODO: add x64, fix issue: LNK1158: cannot run 'cvtres.exe'
platform:
- Win32

# TODO: add VSDebug
configuration:
- Release

install:
- cmd: git clone https://github.com/libyal/libyal.git && move libyal ..\
- ps: .\synczlib.ps1
- ps: .\syncwinflexbison.ps1
- ps: Invoke-WebRequest http://www.cygwin.com/setup-x86.exe -OutFile ..\setup-x86.exe
- cmd: ..\setup-x86.exe -qnNdO -R C:\cygwin -s http://cygwin.mirror.constant.com -l C:\cygwin\var\cache\setup -P bison -P flex
- cmd: git clone https://github.com/joachimmetz/dokan.git && move dokan ..\

build_script:
- ps: .\synclibs.ps1
- ps: .\autogen.ps1
- cmd: if [%TARGET%]==[vs2008] (
    msbuild msvscpp\libfvde.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[vs2010] (
    C:\Python27\python.exe ..\libyal\scripts\msvscpp-convert.py --to 2010 msvscpp\libfvde.sln &&
    msbuild vs2010\libfvde.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[vs2012] (
    C:\Python27\python.exe ..\libyal\scripts\msvscpp-convert.py --to 2012 msvscpp\libfvde.sln &&
    msbuild vs2012\libfvde.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[vs2013] (
    C:\Python27\python.exe ..\libyal\scripts\msvscpp-convert.py --to 2013 msvscpp\libfvde.sln &&
    msbuild vs2013\libfvde.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[vs2015] (
    C:\Python27\python.exe ..\libyal\scripts\msvscpp-convert.py --to 2015 msvscpp\libfvde.sln &&
    msbuild vs2015\libfvde.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[cygwin] (
    xcopy /q /s C:\projects\libfvde C:\cygwin\home\appveyor\ &&
    C:\cygwin\bin\bash -e -l -c "cd libfvde" &&
    C:\cygwin\bin\bash -e -l -c "./synclibs.sh && ./autogen.sh" &&
    C:\cygwin\bin\bash -e -l -c "./configure && make -j4" )
- cmd: if [%TARGET%]==[mingw32] (
    xcopy /q /s C:\projects\libfvde C:\msys64\home\appveyor\ &&
    C:\msys64\usr\bin\bash -e -l -c "cd libfvde" &&
    C:\msys64\usr\bin\bash -e -l -c "./synclibs.sh && ./autogen.sh" &&
    C:\msys64\usr\bin\bash -e -l -c "./configure --host=i686-w64-mingw32 && make -j4" )
- cmd: if [%TARGET%]==[mingw64] (
    xcopy /q /s C:\projects\libfvde C:\msys64\home\appveyor\ &&
    C:\msys64\usr\bin\bash -e -l -c "cd libfvde" &&
    C:\msys64\usr\bin\bash -e -l -c "./synclibs.sh && ./autogen.sh" &&
    C:\msys64\usr\bin\bash -e -l -c "./configure --host=x86_64-w64-mingw32 && make -j4" )

test_script:
- cmd: rem Run tests
- ps: if ($env:TARGET -eq "vs2008") {
    .\runtests.ps1 }
- ps: if ($env:TARGET -eq "vs2010") {
    .\runtests.ps1 }
- ps: if ($env:TARGET -eq "vs2012") {
    .\runtests.ps1 }
- ps: if ($env:TARGET -eq "vs2013") {
    .\runtests.ps1 }
- ps: if ($env:TARGET -eq "vs2015") {
    .\runtests.ps1 }

