environment:
  VisualStudioVersion: 11.0

# TODO: add x64, fix issue: LNK1158: cannot run 'cvtres.exe'
platform:
  - Win32

# TODO: add VSDebug
configuration:
  - Release

install:
  - cmd: git clone https://github.com/libyal/libyal.git && move libyal ..\
  - cmd: git clone https://github.com/joachimmetz/dokan.git && move dokan ..\
  - ps: .\synczlib.ps1
  - ps: .\syncwinflexbison.ps1

before_build:
  - ps: .\synclibs.ps1
  - ps: .\autogen.ps1
  - cmd: ..\win_flex_bison\win_flex.exe -Cf libfvde\libfvde_xml_plist_scanner.l && move lex.yy.c libfvde\libfvde_xml_plist_scanner.c
  - cmd: ..\win_flex_bison\win_bison.exe -d -v -l -p xml_plist_scanner_ libfvde\libfvde_xml_plist_parser.y && move libfvde_xml_plist_parser.tab.c libfvde\libfvde_xml_plist_parser.c && move libfvde_xml_plist_parser.tab.h libfvde\libfvde_xml_plist_parser.h
  - cmd: C:\Python27\python.exe ..\libyal\scripts\msvscpp-convert.py --to 2010 msvscpp\libfvde.sln

build:
  project: vs2010\libfvde.sln

test_script:
  - ps: .\runtests.ps1

