# Build from source on FreeBSD.
name: build_freebsd
on: [push]
permissions: read-all
jobs:
  build_freebsd:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Building from source
      id: build_freebsd
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        mem: 4096
        # Note that the test scripts require bash
        prepare: |
          pkg install -y autoconf automake bash byacc flex fusefs-libs gettext git libtool openssl pkgconf
        run: |
          tests/build.sh
          tests/runtests.sh
